version: '3.8'
services:
  db:
    image: 'postgres:14.8-alpine'
    container_name: 'database'
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_tasks
    networks:
      - fullstack
    volumes:
      - go_tasksDB:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  backend:
    build: .
    container_name: 'backend'
    restart: unless-stopped
    environment:
      DSN: 'postgres://devuser:password@database/go_tasks?sslmode=disable'
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - fullstack

  frontend:
    build: ./frontend
    container_name: 'frontend'
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - fullstack

volumes:
  go_tasksDB:

networks:
  fullstack:
    driver: bridge
