version: '3'
services:
  postgres:
    image: 'postgres:14-alpine'
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_tasks
    volumes:
      - './db-data/postgres/:/var/lib/postgresql/data'
